[package]
name = "benchmark"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { path = "../../crates/common" }
sim-core = { path = "../../crates/sim-core" }
log = { workspace = true }
env_logger = { workspace = true }
